.TH TESTOVAC 1
.SH Nazev
testovac \- Měření zrátovosti a RTT na uzlech
.SH Pouziti
.B ./testovac
[\fB\-h\fR]
[\fB\-u\fR]
[\fB\-t\fR \fI<interval>\fR]
[\fB\-i\fR \fI<interval>\fR]
[\fB\-p\fR \fI<port>\fR]
[\fB\-l\fR \fI<port>\fR]
[\fB\-s\fR \fI<size>\fR]
[\fB\-t\fR \fI<value>\fR]
.IR <uzel1>
.IR <uzel2>
.IR <uzel3>
.IR ...
.SH POPIS
.B testovac
Měří ztrátovost a RTT na zadaných uzlech.

Program odesílá packety a čeká na jejich odpovědi
Podle počtu přijatých odpovědí vypočítá ztrátovost.
.SH OPTIONS
.TP
.BR \-h\fR
Zobrazí nápovědu
.TP
.BR \-u\fR
Zapne testování pomocí protokolu UDP. (Musí být zadaný port
.BR \-p\fR)
.TP
.BR \-p\ \fI<port>\fR
Port pro testování protokolem UDP.
.TP
.BR \-s\ \fI<size>\fR
Velikost dat k odeslání, defaultně 56B nebo 64B pro UDP.
.TP
.BR \-t\ \fI<interval>\fR
Interval za který se vyhodnotí ztrátovost, defaultně 300s.
.TP
.BR \-i\ \fI<interval>\fR
Interval v ms jak často se budou posílat testovací zprávy, defaultně je 100ms.
.TP
.BR \-w\ \fI<timeout>\fR
Doba jak dlouho se čeká na odpověď v sekundách, defaultně je 2s.
.TP
.BR \-l\ \fI<port>\fR
Server listening na daném portu
.TP
.BR \-r\ \fI<value>\fR
Hodnota RTT, vůči které se reportuje překročení.
.BR \fI<uzel>\fR
IPv4/hostname adresa uzlu

Omezení: Neimplementováno IPv6 a UDP (kromě -l).
